/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 finalmatch.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
    console.log(props,'props')
  const { nodes, materials } = useGLTF('../finalmatch.gltf')
  return (

    
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} scale={7} />
    
    </group>
   
  )
}

useGLTF.preload('../finalmatch.gltf')
